{
 "title": "Freqtrade",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(freqtrade_profit_all_coin, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$name % Profit",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "delta(freqtrade_profit_all_percent_sum{name=~\"$name\",name!~\"http://.*\",instance=\"freqtrade_exporter:3000\"}[$__range])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "delta(coin_market_changePercent24Hr{name=\"Bitcoin\",instance=\"crypto_exporter:9101\"}[$__range])",
     "legendFormat": "BTC"
    }
   ]
  },
  {
   "title": "$name $ Profit ",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "targets": [
    {
     "expr": "delta(freqtrade_profit_all_fiat{name=~\"$name\",name!~\"http://.*\",instance=\"freqtrade_exporter:3000\"}[$__range])",
     "legendFormat": "{{name}}",
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "expr": "delta(coin_market_changePercent24Hr{name=\"Bitcoin\",instance=\"crypto_exporter:9101\"}[$__range])",
     "legendFormat": "BTC"
    }
   ]
  },
  {
   "title": "Profits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "targets": [
    {
     "expr": "freqtrade_profit_all_fiat{name=~\"$name\",name!~\"http://.*\",instance=\"freqtrade_exporter:3000\"}",
     "legendFormat": "{{name}}",
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current Open Trades",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "targets": [
    {
     "expr": "freqtrade_status_current_profit_abs{name=~\"$name\"}",
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "expr": "freqtrade_status_open_timestamp{name=~\"$name\"}"
    },
    {
     "expr": "freqtrade_status_current_profit_pct{name=~\"$name\"}"
    }
   ]
  },
  {
   "title": "Trade Statistics",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "freqtrade_losing_trades{name=~\"$name\"}",
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "expr": "freqtrade_winning_trades{name=~\"$name\"}"
    }
   ]
  },
  {
   "title": "Closed Trade Profit over Range",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freqtrade_profit_closed_fiat{name=~\".*\",name!~\"http://.*\"} - freqtrade_profit_closed_fiat{name=~\".*\",name!~\"http://.*\"} offset $__range",
     "legendFormat": "{{name}}",
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Trade Profits Over Interval",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(freqtrade_profit_all_fiat{name=~\".*\",name!~\"http://.*\",instance=\"freqtrade_exporter:3000\"}[$__range])",
     "legendFormat": "{{name}}",
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Trades, Average Profit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "freqtrade_profit_all_ratio_mean{name=~\".*\",name!~\"http://.*\",instance=\"freqtrade_exporter:3000\"}",
     "legendFormat": "{{name}}",
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Trades, Profit Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "freqtrade_profit_all_percent_mean",
     "legendFormat": "{{name}}",
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}